// localStorage actions
export const UPDATE_LOCAL_STORAGE = 'UPDATE_LOCAL_STORAGE';

// location actions
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_ERROR = 'FETCH_LOCATION_ERROR';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_COORDINATES = 'UPDATE_COORDINATES';
export const ERROR_UPDATE_COORDINATES = 'ERROR_UPDATE_COORDINATES';
export const UPDATE_COUNTRY_CODE = 'UPDATE_COUNTRY_CODE';

// weather actions
export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';
export const CHANGE_WEATHER_API = 'CHANGE_WEATHER_API';

// google calendar actions
export const GET_IS_AUTH = 'GET_IS_AUTH';
export const GET_TODOS = 'GET_TODOS';
